## Use the official Ubuntu 18.04 Image from Dockerhub
FROM docker.io/library/ubuntu:18.04

## Set up environment variables so the tzdata install doesn't
## hang on asking for user input for configuration
ARG DEBIAN_FRONTEND="noninteractive"
ARG TZ="America/New_York"

## Install the deps and create the build directory
RUN apt-get update &&\
    apt-get install -y git cmake clang-9 gcc-8 g++-8 gettext help2man\
      libopenblas-dev libfftw3-dev libicu-dev libepoxy-dev libsdl2-dev\
      libfreetype6-dev libpango1.0-dev librsvg2-dev libxml++2.6-dev\
      libavcodec-dev libavformat-dev libswscale-dev libjpeg-dev\
      portaudio19-dev libglm-dev libboost-filesystem-dev\
      libboost-iostreams-dev libboost-locale-dev libboost-system-dev\
      libboost-program-options-dev libssl-dev libcpprest-dev libportmidi-dev\
      libopencv-dev python python3-pip &&\
    pip3 install meson ninja &&\
    apt-get clean &&\
    mkdir /root/performous

## Set the default compiler that cmake will use, otherwise it throws an error.
ENV CC=gcc-8
ENV CXX=g++-8

## Uncomment these to use clang instead
# ENV CC=clang-9
# ENV CXX=clang++-9

## Copy in the build script to make things easy
COPY build_performous.sh /root/performous/build_performous.sh

WORKDIR /root/performous
